import 'package:cloud_firestore/cloud_firestore.dart';

class Produit {
  String id;
  String marque;
  String designation;
  String categorie;
  double prix;
  String photo;
  int quantite;

  Produit({
    required this.id,
    required this.marque,
    required this.designation,
    required this.categorie,
    required this.prix,
    required this.photo,
    required this.quantite,
  });

  factory Produit.fromFirestore(DocumentSnapshot doc) {
    Map data = doc.data() as Map;
    return Produit(
      id: doc.id,
      marque: data['marque'] ?? '',
      designation: data['designation'] ?? '',
      categorie: data['categorie'] ?? '',
      prix: data['prix'] ?? 0.0, // Ensure to specify the type (double)
      photo: data['photo'] ?? '',
      quantite: data['quantite'] ?? 0, // Ensure to specify the type (int)
    );
  }

  // Convertit l'objet Produit en un objet JSON
  Map<String, dynamic> toJson() {
    return {
      'marque': marque,
      'designation': designation,
      'categorie': categorie,
      'prix': prix,
      'photo': photo,
      'quantite': quantite,
    };
  }
}

// This could be in a button's onPressed callback, a form submission function, etc.
void addNewProduct() {
  Produit newProduct = Produit(
    id: '', // Suppose id is auto-generated by Firestore
    marque: "Nike",
    designation: "Air Max",
    categorie: 'Classic running',
    prix: 94.99, // Specify the type (double)
    photo:
        "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/wzitsrb4oucx9jukxsmc/chaussure-air-max-90-pour-dlXJdc.png",
    quantite: 155, // Specify the type (int)
  );

  FirebaseFirestore.instance.collection('produits').add(newProduct.toJson());
}

void deleteProduct(String productId) {
  FirebaseFirestore.instance.collection('produits').doc(productId).delete();
}
